// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;


public class SeltestlinkedinTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void seltestlinkedin() {
    // Test name: seltestlinkedin
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.google.com/");
    // 2 | setWindowSize | 1440x845 | 
    driver.manage().window().setSize(new Dimension(1440, 845));
    // 3 | click | name=q | 
    driver.findElement(By.name("q")).click();
    // 4 | type | name=q | phillip eismark
    driver.findElement(By.name("q")).sendKeys("phillip eismark");
    // 5 | sendKeys | name=q | ${KEY_ENTER}
    driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
    // 6 | runScript | window.scrollTo(0,106.66667175292969) | 
    js.executeScript("window.scrollTo(0,106.66667175292969)");
    // 7 | click | css=.g:nth-child(1) .LC20lb | 
    driver.findElement(By.cssSelector(".g:nth-child(1) .LC20lb")).click();
  }

  @Test
  public void testGoogleSearch() throws InterruptedException {
    WebDriver driver = new ChromeDriver();
    driver.get("http://www.google.com/");
    Thread.sleep(5000);  // Let the user actually see something!
    WebElement searchBox = driver.findElement(By.name("q"));
    searchBox.sendKeys("ChromeDriver");
    searchBox.submit();
    Thread.sleep(5000);  // Let the user actually see something!
    driver.quit();
  }
}
